### ISSUE TITLE
Ledger Live mobile, calling getSigner() after switching accounts results in wrong signer address

### ISSUE THREAD

**Issue by notyouraveragedev** [LedgerHQ/ledger-live-wagmi-connector#11]
Currently when using built-in wagmi hooks on ledger live mobile we get an unique issue where the data is being fetched for the correct account, but the signer it uses is wrong.

Expected behaviour:
- When switching from main account to a secondary one and then back to the main one, the expected signer is the main one

Actual behaviour:
- The signer is the secondary one instead of the main one

Steps to reproduce:
Open Ledger Live mobile
Switch current account to any other
Switch active account back to the original one
getSigner() returns the secondary account instead of the primary resulting in failing transactions

**Comment by chabroA** [comment]
Hey @Tdrachev, thanks for the feedback 🙌 

cc. @adrienlacombe-ledger for triage / prioritization.

In the meantime @Tdrachev, if it's urgent / blocking you, know that the project is open source and contributions are welcome 👍

**Comment by adrienlacombe** [comment]
isn't it weird that issue is with LLM and not LLD @chabroA ?

**Comment by chabroA** [comment]
> isn't it weird that issue is with LLM and not LLD @chabroA ?

@adrienlacombe-ledger Nobody said it was **only** on LLM, from what I understand, but that it was experienced on LLM (maybe @Tdrachev didn't test on LLD)

If this indeed only happen on LLM and not LLD, then it might not necessarily be linked to the connector directly.

Also @Tdrachev, could you test with the [previous version](https://www.npmjs.com/package/@ledgerhq/ledger-live-wagmi-connector/v/0.1.1?activeTab=versions) (`0.1.1`) see if this changes anything.

**Comment by notyouraveragedev** [comment]
@chabroA,
On desktop the issue is not present indeed, using the `getSigner` hook from wagmi returns the correct signer account. Issue is only happening on mobile. 
Was curious wether ledger live mobile works differently than desktop in switching accounts? 
I can try and check the repo when there is more time to see if I can debug  (not necessary blocking at this point).
Also I assumed its the connector as Wagmi calls the connector functions to get data through its hooks. 
Other than that issue could also come from Ledger Live Mobile itself.

**Comment by chabroA** [comment]
Wild guess would be that the issue indeed comes from LLM rather than the connector since only LLM is impacted and not LLD
