### ISSUE TITLE
Support for ETH & MATIC testnets?

### ISSUE THREAD

**Issue by schnogz** [LedgerHQ/ledger-live-wagmi-connector#5]
Reading over the docs [here](https://developers.ledger.com/docs/dapp/dapp-customisation/), i see that it states
```
- We currently supports Ethereum mainnet, BSC and Polygon POS chains.
```

However in your eth-dapp-browser [repo](https://github.com/LedgerHQ/eth-dapp-browser#readme) i see in the example manifest
```
{
        "currency": "ethereum_goerli",
        "chainID": 5,
        "nodeURL": "https://eth-goerli.g.alchemy.com/v2/vzJoUrfWDBOdwtCL-sybfBzIfNzY0_tk"
      }
```

So what is the truth here, is there testnet support for local development?  Specifically interested in ETH Goerli, Kovan and MATIC Mumbai.

**Comment by adrienlacombe** [comment]
hi, yes sorry in the docs we only listed prod environnements, I will add the testnets too. We only have goerli; not kovan, not mumbai sorry.

**Comment by chabroA** [comment]
Hi @schnogz, thanks for your feedback.

Indeed as mentioned by @adrienlacombe-ledger (and as seen on the eth-dapp-browser example manifest), the ethereum goerli testnet is supported.

ℹ️  To use the Goerli Testnet network, make sur you have a Goerli Testnet account available in Ledger Live (to enable testnet networks, head over to settings -> experimental features and turn on the developer mode setting).

**Comment by schnogz** [comment]
thanks for the information guys!

Any plans to add polygon testnet support?

**Comment by schnogz** [comment]
I am not seeing Goerli show up in local dapp.  here is my config

```
"networks": [
      {
        "currency": "ethereum",
        "chainID": 1,
        "nodeURL": "https://mainnet.infura.io/v3/xxx"
      },
      {
        "currency": "ethereum_goerli",
        "chainID": 5,
        "nodeURL": "https://goerli.infura.io/v3/xxx"
      },
      {
        "currency": "polygon",
        "chainID": 137,
        "nodeURL": "https://polygon-rpc.com/xxx"
      }
    ]
```
    
Should Goerli be available from the dropdown?
    
![Screen Shot 2022-09-20 at 9 24 46 AM](https://user-images.githubusercontent.com/6364918/191269639-d7a1daf1-92f2-4b4d-86ae-91635b1922c0.png)

**Comment by schnogz** [comment]
nevermind my comment above. i realized i had to add the ETH Goerli account in Ledger Live and then it showed up in the list in my dapp

**Comment by adrienlacombe** [comment]
yup, well done! No plan to add Mumbai at the moment.
