### ISSUE TITLE
Type errors with Wagmi as of version 0.6.0

### ISSUE THREAD

**Issue by geositta** [LedgerHQ/ledger-live-wagmi-connector#6]
Am unable to use the ledger live wagmi connector with wagmi as of wagmi version 0.6.0.
Current version of wagmi is `0.8.7`

I have added IFrameEthereumConnector as per the example.

```
import { IFrameEthereumConnector } from '@ledgerhq/ledger-live-wagmi-connector';

export const client = createClient({
  autoConnect: true,
  connectors: [
    new MetaMaskConnector({ chains }),
    new IFrameEthereumConnector({ chains, options: {} }),
  ],
  provider,
});
```

However I see various type errors including:

- `Type 'IFrameEthereumConnector' is not assignable to type 'Connector<any, any, any>'.`
- `Types of property 'chains' are incompatible.`

**Comment by chabroA** [comment]
Hey @geositta, thanks for your feedback! 🙌 

Indeed the dependency of wagmi used by our connector is currently set to `^0.5.5`, we might need to update this dependance to make the connector compatible with newer versions of the lib that might have brought breaking changes.

I took a quick look at it and was able to make our [smoke test](https://github.com/LedgerHQ/ledger-live-wagmi-connector/blob/main/test/index.test.ts) pass with wagmi dependency up to `^0.7.0`.

We will need to take a deeper look at this. Could you share a minimal reproductible example / project where you are encountering this error so that we can properly investigate?

Many thanks

**Comment by geositta** [comment]
> Hey @geositta, thanks for your feedback! 🙌
Thanks for your response @chabroA. I made a create wagmi project where you should be able to see the type error locally.
https://github.com/geositta/wagmi-vite-react

There appears to be a completely separate issue when running `npm run dev` 
`Failed to resolve entry for package "@ledgerhq/iframe-provider"`

**Comment by chabroA** [comment]
Hey @geositta,

The connector library has been updated and the latest version `0.2.0` includes, among other things, an update of the wagmi dependency that should solve your issue 👍

**Comment by geositta** [comment]
@chabroA thank you, that seems to have worked for the type error, but when I go to run the app with `npm run dev` there is a separate issue:
`Failed to resolve entry for package "@ledgerhq/iframe-provider". The package may have incorrect main/module/exports specified in its package.json`

https://github.com/geositta/wagmi-vite-react

**Comment by geositta** [comment]
@chabroA also a second issue that I am able to recreate in two different repos is a problem with how ethers/lib/utils is imported.
https://github.com/geositta/wagmi-ledger-live

```
Compiled with problems:

ERROR in ./node_modules/@ledgerhq/ledger-live-wagmi-connector/lib/index.js 3:0-56

Module not found: Error: Can't resolve 'ethers/lib/utils' in '/wagmi-ledger-live/node_modules/@ledgerhq/ledger-live-wagmi-connector/lib'
Did you mean 'utils.js'?
BREAKING CHANGE: The request 'ethers/lib/utils' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.
```

**Comment by alleycat0001** [comment]
> @chabroA also a second issue that I am able to recreate in two different repos is a problem with how ethers/lib/utils is imported. https://github.com/geositta/wagmi-ledger-live
> 
> ```
> Compiled with problems:
> 
> ERROR in ./node_modules/@ledgerhq/ledger-live-wagmi-connector/lib/index.js 3:0-56
> 
> Module not found: Error: Can't resolve 'ethers/lib/utils' in '/wagmi-ledger-live/node_modules/@ledgerhq/ledger-live-wagmi-connector/lib'
> Did you mean 'utils.js'?
> BREAKING CHANGE: The request 'ethers/lib/utils' failed to resolve only because it was resolved as fully specified
> (probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
> The extension in the request is mandatory for it to be fully specified.
> Add the extension to the request.
> ```

@chabroA this is still an issue it looks like with `0.4.0` on ethers `5.7.2`.
