### ISSUE TITLE
Update Wagmi depedency version

### ISSUE THREAD

**Issue by schnogz** [LedgerHQ/ledger-live-wagmi-connector#8]
The latest version of Wagmi is `0.8.10` and it contains many bug fixes, quality of life improvements and TS typings updates. Your currently required version is `^0.5.5` and due to the wide discrepancy in versions, it is causing me trouble of updating wagmi in my app.

Please upgrade to latest version soon.

**Comment by chabroA** [comment]
Hey @schnogz! Thanks for your feedback. Indeed, the wagmi lib is moving fast lately, a new version of the connector (`0.2.0`) has been published today including an update of the wagmi lib (to `^0.8.8` so it should work with `0.8.10` as well).

Don't hesitate to open PRs if you see improvements, regarding dependencies version or anything else you deem needed. This repo is open to external contributions and contributions are very welcome and highly appreciated 🧑‍💻
